const express = require('express');
const router = express.Router();
const { createMeeting, getMeetings, getMeetingById, updateMeeting, deleteMeeting, joinMeeting } = require('../controllers/meetingController');
const { endMeeting } = require('../controllers/aiController');
const protect = require('../middleware/authMiddleware');
router.post('/', protect, createMeeting);
router.post('/join', protect, joinMeeting);
router.get('/', protect, getMeetings);
router.get('/:id', protect, getMeetingById);
router.put('/:id', protect, updateMeeting);
router.delete('/:id', protect, deleteMeeting);
router.post('/:id/end-meeting', protect, endMeeting);
module.exports = router;
